Repository NicholasBarreyre/SEProject, pull requests merged in 2018-02, with the labels that each got.

#3 Readme update -Iteration 1 information
  README.md
Labels: Priority: Medium, Status: Review Needed, Type: Project Management

#15 Blank Application code [LUNN/BARRERYRE]
  .gitignore
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/runConfigurations.xml
  .idea/vcs.xml
  README.md
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/ca/dal/cs/athletemonitor/athletemonitor/ExampleInstrumentedTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/ca/dal/cs/athletemonitor/athletemonitor/MainActivity.java
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/ca/dal/cs/athletemonitor/athletemonitor/ExampleUnitTest.java
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: Priority: High, Status: Accepted

#16 Solved issue with CircleCI build failing. [LUNN]
  .circleci/config.yml
  .idea/misc.xml
  README.md
  gradlew
  licenses/android-sdk-license
  licenses/android-sdk-preview-license
Labels: Status: Review Needed

#18 Fix failing activity creation [Wilkins]
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules.xml
Labels: Priority: High, Type: Bug

#19 US1 Complete
  .gitignore
  README.md
  app/build.gradle
  app/google-services.json
  app/src/androidTest/java/ca/dal/cs/athletemonitor/athletemonitor/AccountManagerTest.java
  app/src/androidTest/java/ca/dal/cs/athletemonitor/athletemonitor/LoginActivityUITest.java
  app/src/androidTest/java/ca/dal/cs/athletemonitor/athletemonitor/testhelpers/TestingHelper.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/ca/dal/cs/athletemonitor/athletemonitor/AccountManager.java
  app/src/main/java/ca/dal/cs/athletemonitor/athletemonitor/LoginActivity.java
  app/src/main/java/ca/dal/cs/athletemonitor/athletemonitor/MainActivity.java
  app/src/main/java/ca/dal/cs/athletemonitor/athletemonitor/User.java
  app/src/main/java/ca/dal/cs/athletemonitor/athletemonitor/listeners/BooleanResultListener.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: Priority: High, Status: Review Needed

#22 Completes US2 - Create an account (LUNN/BARREYRE)
  app/src/androidTest/java/ca/dal/cs/athletemonitor/athletemonitor/AccountManagerTest.java
  app/src/androidTest/java/ca/dal/cs/athletemonitor/athletemonitor/LoginActivityUITest.java
  app/src/androidTest/java/ca/dal/cs/athletemonitor/athletemonitor/testhelpers/TestingHelper.java
  app/src/main/java/ca/dal/cs/athletemonitor/athletemonitor/AccountManager.java
  app/src/main/java/ca/dal/cs/athletemonitor/athletemonitor/LoginActivity.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Needed

#21 Us58 logout
  .idea/misc.xml
  app/src/androidTest/java/ca/dal/cs/athletemonitor/athletemonitor/AccountManagerTest.java
  app/src/androidTest/java/ca/dal/cs/athletemonitor/athletemonitor/MainActivityTest.java
  app/src/main/java/ca/dal/cs/athletemonitor/athletemonitor/AccountManager.java
  app/src/main/java/ca/dal/cs/athletemonitor/athletemonitor/MainActivity.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Needed

#24 US28 Complete - View and Edit User Information
  .idea/codeStyleSettings.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/google-services.json
  app/src/androidTest/java/ca/dal/cs/athletemonitor/athletemonitor/ExampleInstrumentedTest.java
  app/src/androidTest/java/ca/dal/cs/athletemonitor/athletemonitor/MainActivityTest.java
  app/src/androidTest/java/ca/dal/cs/athletemonitor/athletemonitor/UserInformationActivityUnitTests.java
  app/src/androidTest/java/ca/dal/cs/athletemonitor/athletemonitor/UserInformationEditActivityUnitTests.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/ca/dal/cs/athletemonitor/athletemonitor/MainActivity.java
  app/src/main/java/ca/dal/cs/athletemonitor/athletemonitor/UserInformation.java
  app/src/main/java/ca/dal/cs/athletemonitor/athletemonitor/UserInformationActivity.java
  app/src/main/java/ca/dal/cs/athletemonitor/athletemonitor/UserInformationEditActivity.java
  app/src/main/java/ca/dal/cs/athletemonitor/athletemonitor/utilities/StringJoiner.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_user_information.xml
  app/src/main/res/layout/activity_user_information_edit.xml
  app/src/main/res/layout/content_user_information.xml
  app/src/main/res/layout/content_user_information_edit.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/ca/dal/cs/athletemonitor/athletemonitor/ExampleUnitTest.java
  app/src/test/java/ca/dal/cs/athletemonitor/athletemonitor/UserInformationUnitTests.java
  app/src/test/java/ca/dal/cs/athletemonitor/athletemonitor/utilities/StringJoinerUnitTests.java
  build.gradle
Labels: Priority: High, Status: Review Needed

#25 US28 Bug Fix - Edit new user info
  .idea/misc.xml
  app/src/main/java/ca/dal/cs/athletemonitor/athletemonitor/UserInformationActivity.java
Labels: Priority: High, Status: Review Needed
